name: audio_recorder_app
description: A Flutter audio recorder application.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  envied: ^1.1.1
  uuid: ^4.5.1
  flutter_riverpod: ^2.4.9
  record: ^5.2.0
  audioplayers: ^6.2.0
  path_provider: ^2.1.5
  permission_handler: ^11.3.1
  intl: ^0.20.2
  riverpod_annotation: ^2.6.1
  rxdart: ^0.28.0
  googleapis: 13.2.0
  googleapis_auth: 1.6.0
  gcloud: 0.8.18
  mime: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  analyzer: 6.3.0
  flutter_lints: ^5.0.0
  build_runner: ^2.4.11
  riverpod_generator: ^2.3.9
  envied_generator: ^1.1.1

flutter:
  uses-material-design: true

  assets:
    - credentials/credentials.json
